timezone: America/Vancouver
permalink: /:categories/:title/
baseurl: /bmtm

prose:
  rooturl: '_posts'
  media: 'media'
  metadata:
    _posts/news:
      - name: "title"
        field:
          element: "text"
          label: "News Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "news"
      - name: "category"
        field:
          element: "hidden"
          value: "news"
      - name: "author"
        field:
          element: "text"
          label: "Author Name"
          value: ""
            